# Generated by Django 2.1.5 on 2019-10-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='usernmae',
            new_name='usernamae',
        ),
    ]
