# Generated by Django 2.1.5 on 2020-01-13 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0004_auto_20191201_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='displayname',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='icon',
        ),
    ]
