# Generated by Django 2.1.5 on 2020-01-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0005_auto_20200113_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='username',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='appuser',
            name='icon',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='user_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
